require 'factory_girl'
Dir[Rails.root.join("spec/factories/*.rb")].each { |f| require f }

User.all.map(&:destroy)
Spot.all.map(&:destroy)
Reservation.all.map(&:destroy)
ReservationAttempt.all.map(&:destroy)

user = Factory.create(:verified_user)

State.create(:abbreviation=>"AR",:name=>"Arkansas")
State.create(:abbreviation=>"DC",:name=>"Washington, D.C.")
State.create(:abbreviation=>"DE",:name=>"Delaware")
State.create(:abbreviation=>"FL",:name=>"Florida")
State.create(:abbreviation=>"GA",:name=>"Georgia")
State.create(:abbreviation=>"KS",:name=>"Kansas")
State.create(:abbreviation=>"LA",:name=>"Louisiana")
State.create(:abbreviation=>"MD",:name=>"Maryland")
State.create(:abbreviation=>"MO",:name=>"Missouri")
State.create(:abbreviation=>"MS",:name=>"Mississippi")
State.create(:abbreviation=>"NC",:name=>"North Carolina")
State.create(:abbreviation=>"OK",:name=>"Oklahoma")
State.create(:abbreviation=>"SC",:name=>"South Carolina")
State.create(:abbreviation=>"TN",:name=>"Tennessee")
State.create(:abbreviation=>"TX",:name=>"Texas")
State.create(:abbreviation=>"WV",:name=>"West Virginia")
State.create(:abbreviation=>"AL",:name=>"Alabama")
State.create(:abbreviation=>"CT",:name=>"Connecticut")
State.create(:abbreviation=>"IA",:name=>"Iowa")
State.create(:abbreviation=>"IL",:name=>"Illinois")
State.create(:abbreviation=>"IN",:name=>"Indiana")
State.create(:abbreviation=>"ME",:name=>"Maine")
State.create(:abbreviation=>"MI",:name=>"Michigan")
State.create(:abbreviation=>"MN",:name=>"Minnesota")
State.create(:abbreviation=>"NE",:name=>"Nebraska")
State.create(:abbreviation=>"NH",:name=>"New Hampshire")
State.create(:abbreviation=>"NJ",:name=>"New Jersey")
State.create(:abbreviation=>"NY",:name=>"New York")
State.create(:abbreviation=>"OH",:name=>"Ohio")
State.create(:abbreviation=>"RI",:name=>"Rhode Island")
State.create(:abbreviation=>"VT",:name=>"Vermont")
State.create(:abbreviation=>"WI",:name=>"Wisconsin")
State.create(:abbreviation=>"CA",:name=>"California")
State.create(:abbreviation=>"CO",:name=>"Colorado")
State.create(:abbreviation=>"NM",:name=>"New Mexico")
State.create(:abbreviation=>"NV",:name=>"Nevada")
State.create(:abbreviation=>"UT",:name=>"Utah")
State.create(:abbreviation=>"AZ",:name=>"Arizona")
State.create(:abbreviation=>"ID",:name=>"Idaho")
State.create(:abbreviation=>"MT",:name=>"Montana")
State.create(:abbreviation=>"ND",:name=>"North Dakota")
State.create(:abbreviation=>"OR",:name=>"Oregon")
State.create(:abbreviation=>"SD",:name=>"South Dakota")
State.create(:abbreviation=>"WA",:name=>"Washington")
State.create(:abbreviation=>"WY",:name=>"Wyoming")
State.create(:abbreviation=>"HI",:name=>"Hawaii")
State.create(:abbreviation=>"AK",:name=>"Alaska")
State.create(:abbreviation=>"KY",:name=>"Kentucky")
State.create(:abbreviation=>"MA",:name=>"Massachusetts")
State.create(:abbreviation=>"PA",:name=>"Pennsylvania")
State.create(:abbreviation=>"VA",:name=>"Virginia")